sqa_criteria:
   qc_style:
     repos:
       arrebol:
         container: arrebol-testing
         commands:
           - ls /saps-arrebol-repo
           - mvn -f /saps-arrebol-repo/pom.xml spotless:check
