sqa_criteria:
   qc_style:
     repos:
       arrebol:
         container: arrebol-testing
         commands:
           - mvn -f /saps-arrebol-repo/pom.xml spotless:apply
           - mvn -f /saps-arrebol-repo/pom.xml spotless:check
