config:
  project_repos:
    arrebol:
      repo: 'https://github.com/EOSC-synergy/arrebol'
      branch: feature/k8s-executor
      #dockerhub: ufcglsd/arrebol
      #dockertag: k8s

sqa_criteria:
   qc_style:
     repos:
       arrebol:
         container: arrebol-testing
         commands:
           - mvn -f /saps-arrebol-repo/pom.xml spotless:check
